<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2010 Sopra Steria Group (movalys.support@soprasteria.com)

    This file is part of Movalys MDK.
    Movalys MDK is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Movalys MDK is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Lesser General Public License for more details.
    You should have received a copy of the GNU Lesser General Public License
    along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.

-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<!-- **********************************************************************
***** controllerType='FORMVIEW' or 'FIXEDLISTVIEW'  > subView **********-->

<xsl:template match="subView[customClass='UILabel' or customClass='MDKLabel']" mode="gen-table-cell">
	<xsl:param name="controllerId"/>
	<xsl:param name="posY"/>
	<xsl:param name="viewId"/>	
	<xsl:comment> [cell-others.xsl] subView[UILabel ou MDKLabel] (controllerId=<xsl:value-of select="$controllerId"/>,posY=<xsl:value-of select="$posY"/>,viewId=<xsl:value-of select="$viewId"/>) </xsl:comment>
				
		<!-- 
		Nothing to do because the label associated to a field is generated by the template handling this field.
		The label is also in the input XML only for information.
		-->
		
	<xsl:comment>
		********** WARNING ************
			The subView '<xsl:value-of select="customClass"/>' is not handled by the generator when controllerType='FORMVIEW' or 'FIXEDLISTVIEW' .
			It should not be in the input XML.
		*******************************
	</xsl:comment>
		
</xsl:template>

<xsl:template match="subView[customClass=*]" mode="gen-table-cell" priority="-1000">
	<xsl:param name="controllerId"/>
	<xsl:param name="posY"/>
	<xsl:param name="viewId"/>
	

	<xsl:comment>
		********** WARNING ************
			The subView '<xsl:value-of select="customClass"/>' is not handled by the generator when controllerType='FORMVIEW' or 'FIXEDLISTVIEW' 
		*******************************
	</xsl:comment>
</xsl:template>

</xsl:stylesheet>